# HTTP Server.
[server]
	address        = ":8199"
	serverRoot     = "public"
	serverAgent    = "fuck you"
	logPath        = "./log/server"
	nameToUriType  = 2
	routeOverWrite = true
    clientMaxBodySize = 524288000   #52428800 50M  当前设置500M
# Logger configurations.
[logger]
    path   = "./log"
    level  = "all"
    stdout = true

# Template view configurations.
[viewer]
    path        = "template"
    defaultFile = "index.html"

# Database configurations.
[database]
    link  = "mysql:root:123321@tcp(127.0.0.1:3306)/goerp"
    debug = true
    # 数据库日志对象配置
    [database.logger]
        Path   = "./log/sql"
        Level  = "all"
        Stdout = true
# Redis数据库配置
[redis]
    default = "127.0.0.1:6379,0"
    cache   = "127.0.0.1:6379,1,123456?idleTimeout=600"



# JWT 验证
[jwt]
    jwtSecret = "kQH5cZam58SsYpMHaycgpz9X2dGb8cZwN8mkr5rw2Hjl56ww9lfTD6rR8w7lFPMK"
    #默认1个小时，这里设置2小时
    ttl=2
    #bearer测试用永久token设置
    bearer="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE5NzgxOTM1ODQsImlhdCI6MTYxODE5MzU4NCwicm9sZSI6InVzZXIiLCJzdWIiOjF9.Kk5uKpKjXLkdudHtUz5u41KJLabVke8uWe33vmxprQ0"
   # bearer="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MTg0ODUwMTAsImlhdCI6MTYxODQ3NzgxMCwicm9sZSI6InVzZXIiLCJzdWIiOjN9.nVefqNyuBJY7C-IsmOLLEqbAP7c_y9FD_N0SqtZEFmE"
# GF-CLI工具配置
[gfcli]
    # 自定义DAO生成配置(默认是读取database配置)
    [[gfcli.gen.dao]]
        link   = "mysql:root:123321@tcp(127.0.0.1:3306)/goerp"
        group  = "default"
        jsonCase ="Snake"
        tables = "user,group,menu,role,setting,steel,wechat,goods,order"
    [gfcli.build]
        name     = "tonicgb"
        arch     = "amd64"
        system   = "linux,windows"
        mod      = "none"
        cgo      = 0
        pack     = "public,template,config"
        version  = "v1.0.0"
        output   = "./bin"
        extra    = ""


